version: '3.8'

services:
  stats-service:
    build: ewm-stats-service/stats-service
    image: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_NAME=ewm-stats-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-service-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm-stats-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_HOST=ewm-db
      - DB_NAME=ewm-main-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-service-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm-main-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
