CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.endpoint_hit (
    id        BIGINT                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    app       VARCHAR(64)                 NOT NULL,
    uri       VARCHAR(256)                NOT NULL,
    ip        VARCHAR(15)                 NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);